wykon: main.o lib.o
	
	g++ main.o lib.o -o wykon



lib.o: lib.h
	
	g++ -Wall -c lib.h -o lib.o



main.o: main.cpp lib.h
	
	g++ -Wall -c main.cpp -o main.o



.PHONY: clean



clean:
	
	rm -f kod1.o dodawanie.o wykon
run:
	

./wykon

